filebeat.inputs:
  - type: container
    paths:
      - '/var/lib/docker/containers/*/*.log'
      - '/var/lib/containers/**/*.log'

processors:
  - add_docker_metadata:
      host: "unix:///var/run/docker.sock"
      match_source_index: 3
  - decode_json_fields:
      fields: ["message"]
      target: "json"
      overwrite_keys: true

output.logstash:
  hosts: ["s4-logstash:5044"]
  indices:
    - index: "filebeat-%{[agent.version]}-%{+yyyy.MM.dd}"

logging.json: true
logging.metrics.enabled: false