FROM registry.access.redhat.com/ubi8/openjdk-17@sha256:eea016e9e3d7da20822d7e62ab6566a5b2084c73f598b8379cec977dd08fbf65

ENV LANG="en_US.UTF-8" LANGUAGE="en_US:en"

COPY --chown=185 target/emptydir /deployment
COPY --chown=185 target/*.jar /deployment/app.jar

USER 185
WORKDIR /deployment

ENTRYPOINT [ "java", "-jar", "app.jar" ]

