# JRE 17:
# Source: https://console.cloud.google.com/gcr/images/distroless/global/java17@sha256:d8e3ff1283abe92f7aa12ed4d8156d0ef04bf44e7d7c54a48c821444587fbc97
FROM gcr.io/distroless/java17@sha256:d8e3ff1283abe92f7aa12ed4d8156d0ef04bf44e7d7c54a48c821444587fbc97

ENV LANG="en_US.UTF-8" LANGUAGE="en_US:en"

COPY --chown=185 target/emptydir /deployment
COPY --chown=185 target/*.jar /deployment/app.jar

USER 185
WORKDIR /deployment

ENTRYPOINT [ "java", "-jar", "app.jar" ]

