FROM registry.access.redhat.com/ubi8/openjdk-17@sha256:0eea1d20aaa26041edf26b925fb204d839e5b93122190191893a0299b2e1b589

ENV LANG="en_US.UTF-8" LANGUAGE="en_US:en"

USER 185
WORKDIR /deployment

COPY \
  --chown=185 \
  --chmod=555 \
  target/quarkus-app/lib/ /deployment/lib/
COPY \
  --chown=185 \
  --chmod=555 \
  target/quarkus-app/*.jar /deployment/
COPY \
  --chown=185 \
  --chmod=555 \
  target/quarkus-app/app/ /deployment/app/
COPY \
  --chown=185 \
  --chmod=555 \
  target/quarkus-app/quarkus/ /deployment/quarkus/

ENTRYPOINT [ "java", "-jar", "quarkus-run.jar" ]