FROM registry.access.redhat.com/ubi8/openjdk-17@sha256:0eea1d20aaa26041edf26b925fb204d839e5b93122190191893a0299b2e1b589

ENV LANG="en_US.UTF-8" LANGUAGE="en_US:en"

USER 185
WORKDIR /deployment

COPY \
  --chown=185 \
  --chmod=555 \
  target/quarkus-app/lib/ /deployment/lib/
COPY \
  --chown=185 \
  --chmod=555 \
  target/quarkus-app/*.jar /deployment/
COPY \
  --chown=185 \
  --chmod=555 \
  target/quarkus-app/app/ /deployment/app/
COPY \
  --chown=185 \
  --chmod=555 \
  target/quarkus-app/quarkus/ /deployment/quarkus/
ENV JAVA_APP_DIR="/deployment"
ENV JAVA_APP_JAR="${JAVA_APP_DIR}/quarkus-run.jar"
ENV JAVA_OPTS="-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager"
ENTRYPOINT [ "/opt/jboss/container/java/run/run-java.sh" ]