FROM registry.access.redhat.com/ubi8/openjdk-17@sha256:0eea1d20aaa26041edf26b925fb204d839e5b93122190191893a0299b2e1b589

ENV LANG="en_US.UTF-8" LANGUAGE="en_US:en"

USER 185
WORKDIR /deployment

COPY \
  --chown=185 \
  --chmod=555 \
  target/*.jar /deployment/app.jar

ENV JAVA_APP_DIR="/deployment"
ENV JAVA_APP_JAR="${JAVA_APP_DIR}/app.jar"
ENTRYPOINT [ "/opt/jboss/container/java/run/run-java.sh" ]