# 2.0
FROM quay.io/quarkus/quarkus-micro-image@sha256:8b22a0cadc42d2140ceb35175c9fed6cafc7f46edcbb9c1044cab974ca470310

COPY --chown=185 target/emptydir /deployment
COPY --chown=185 target/*-runner /deployment/quarkus-run

USER 185
WORKDIR /deployment

ENTRYPOINT ["./quarkus-run", "-Dquarkus.http.host=0.0.0.0"]