FROM registry.access.redhat.com/ubi8/openjdk-17@sha256:0eea1d20aaa26041edf26b925fb204d839e5b93122190191893a0299b2e1b589

ENV LANG="en_US.UTF-8" LANGUAGE="en_US:en"

USER 185
WORKDIR /deployment

COPY --chown=185 target/*.jar /deployment/app.jar

ENTRYPOINT [ "java", "-jar", "app.jar" ]

