quarkus:
  datasource:
    db-kind: postgresql
    username: ${DB_USERNAME:upload}
    password: ${DB_PASSWORD:upload}
    jdbc:
      driver: io.opentracing.contrib.jdbc.TracingDriver
      url: jdbc:tracing:${quarkus.datasource.db-kind}://${DB_HOST:localhost:5432}/${DB_NAME:upload}
      min-size: ${DB_MIN_SIZE:2}
      max-size: ${DB_MAX_SIZE:8}
  devservices:
    enabled: false
  http:
    port: 8081
  jaeger:
    enabled: ${TRACING_ENABLED:true}
    endpoint: ${TRACING_ENDPOINT:http://localhost:14268/api/traces}
    service-name: aggregator
    sampler-type: const
    sampler-param: 1
  log:
    console:
      format: '%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c{3.}] [%X{CorrelationID}] (%t) %s%e%n'
    handler:
      gelf:
        enabled: ${GELF_ENABLED:true}
        include-full-mdc: true
        host: ${GELF_HOST:localhost}
        port: ${GELF_PORT:12201}
        additional-field:
          app:
            type: String
            value: aggregator
          pod:
            type: String
            value: ${POD_NAME:aggregator-0}
mp:
  messaging:
    incoming:
      amqp-upload-ready-for-processing-incoming:
        address: upload-ready-for-processing::aggregator
        connector: smallrye-amqp
        durable: true
        host: ${AMQP_HOST:localhost}
        port: ${AMQP_PORT:5672}
        username: ${AMQP_USERNAME:artemis}
        password: ${AMQP_PASSWORD:artemis}