quarkus:
  datasource:
    db-kind: postgresql
    username: ${DB_USERNAME:upload}
    password: ${DB_PASSWORD:upload}
    jdbc:
      url: jdbc:${quarkus.datasource.db-kind}://${DB_HOST:localhost:5432}/${DB_NAME:upload}
      min-size: ${DB_MIN_SIZE:2}
      max-size: ${DB_MAX_SIZE:8}
      telemetry: true
  devservices:
    enabled: false
  hibernate-orm:
    dialect: org.hibernate.dialect.PostgreSQLDialect
  http:
    port: 8081
  log:
    console:
      format: '%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c{3.}] [%X] (%t) %s%e%n'
      json:
        ~: ${CONSOLE_LOG_JSON:false}
        exception-output-type: formatted
    handler:
      gelf:
        enabled: ${GELF_ENABLED:false}
        include-full-mdc: true
        host: ${GELF_HOST:localhost}
        port: ${GELF_PORT:12201}
  native:
    additional-build-args: -J-Xmx4g
  otel:
    enabled: true
    exporter:
      otlp:
        endpoint: ${OTLP_HOST:http://localhost:4317}
mp:
  messaging:
    incoming:
      amqp-upload-ready-for-processing-incoming:
        address: upload-ready-for-processing::aggregator
        connector: smallrye-amqp
        durable: true
        host: ${AMQP_HOST:localhost}
        port: ${AMQP_PORT:5672}
        username: ${AMQP_USERNAME:artemis}
        password: ${AMQP_PASSWORD:artemis}